title: "Office Security Settings Changed"
description: |
    This analytic detects registry changes to Office macro settings. This could be an indication an attacker is trying to execute a dynamic macro, as seen used by APT37. Possible FP's are valid macros, group policy changes, or a user manually changing office security settings. Modified SIGMA rule from the main repo and included additional references.
    

rank: Medium
tags: 
    - attack.defense_evasion
    - attack.T1112
author: Trent Liffick (@tliffick)
references: 
    - "https://blog.malwarebytes.com/threat-analysis/2021/01/retrohunting-apt37-north-korean-apt-used-vba-self-decode-technique-to-inject-rokrat/"
    - "https://www.virustotal.com/gui/file/3c59ad7c4426e8396369f084c35a2bd3f0caa3ba1d1a91794153507210a77c90/behavior/C2AE"
logsource:
    category: registry_value_change
detection: 
    condition: sec_settings
    sec_settings:
        TargetObject|endswith:
            - \Security\Trusted Documents\TrustRecords
            - \Security\AccessVBOM
            - \Security\VBAWarnings
        EventType:
            - SetValue
            - DeleteValue
            - CreateValue
